// REDUX ACTION TYPES
export const SEARCH_USERS = 'SEARCH_USERS'
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL'
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS'
export const USERS_EMPTY = 'USERS_EMPTY'
export const SEARCH_REPOS = 'SEARCH_REPO'
export const SEARCH_REPOS_FAIL = 'SEARCH_REPOS_FAIL'
export const SEARCH_REPOS_SUCCESS = 'SEARCH_REPOS_SUCCESS'
export const REPOS_EMPTY = 'REPOS_EMPTY'